version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile # Corrected case
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile # Corrected case
    ports:
      - "5173:80"
    depends_on:
      - backend
