# for deploying the frontend app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sidh146/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_BACKEND_URL
              value: "http://backend-service:5000"
