name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Backend/Dockerfile
          push: true
          tags: yourdockerhubusername/backend:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Frontend/Dockerfile
          push: true
          tags: yourdockerhubusername/frontend:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
          kubectl --kubeconfig=kubeconfig apply -f k8s/
          kubectl --kubeconfig=kubeconfig rollout restart deployment/frontend-deployment
          kubectl --kubeconfig=kubeconfig rollout restart deployment/backend-deployment
